environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  - "build.cmd %PYTHON%\\Scripts\\pyinstaller --onefile bsmh/bsmh.py --name bsmh"
  - cmd: "C:\\projects\\bsmh\\dist\\bsmh.exe"

artifacts:
  - path: dist\bsmh.exe

deploy:
  - provider: GitHub
    release: bsmh-v$(appveyor_build_version)
    description: ''
    auth_token:
      secure: P6QF2KUniooo2VpHVHCBi/C/f8g5kaGLaRIJAvY6WH/JQKB3Li6y0gtVjkpMc8Ry
    artifact: dist\bsmh.exe
    draft: false
    prerelease: false
    on:
      branch: main                 # release from master branch only

      #APPVEYOR_REPO_TAG: true        # deploy on tag push only
